<script type="text/javascript">
//    var head= document.getElementsByTagName('head')[0];
//
//    var script= document.createElement('script');
//    script.type= 'text/javascript';
//
//
//
//    script.setAttribute( 'data-public-key',"<?php //echo $this->getPublicKey() ?>//");
//    script.setAttribute( 'data-user-email',"<?php //echo $this->getEmailAddress() ?>//");
//    script.setAttribute( 'data-amount',"<?php //echo $this->getAmount()?>//");
//    script.setAttribute( 'data-currency',"<?php //echo $this->getCurrency()?>//");
//
//
//    script.src= 'http://ckofe.com/js/Checkout.js';
//
//    head.appendChild(script);


</script>

 <script async src="http://ckofe.com/js/CKOAPI.js"></script>